### ISSUE TITLE
Crash on android 12

### ISSUE THREAD

**Issue by namnguyen211** [Shopify/flash-list#572] opened 2022-08-24 07:13 UTC
## Platform:

- [ ] iOS
- [x] Android

## Environment

^1.2.1

**Comment by fortmarek** [comment] 2022-08-24 12:35
Hey, we'll need more information, closing until such information is provided.

**Closed by fortmarek** 2022-08-24 12:35 UTC
Labels: bug

**Comment by namnguyen211** [comment] 2022-08-25 03:57
i updated issue

**Comment by fortmarek** [comment] 2022-08-30 10:38
Unfortunately, we can't reproduce an issue like this. Please, provide a reproducible sample with steps.
