### ISSUE TITLE
Having crash on android

### ISSUE THREAD

**Issue by namnguyen211** [Shopify/flash-list#573] opened 2022-08-26 04:39 UTC
it's happen when i run on real device or emulator android 12
> signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x20
Cause: null pointer dereference
x0 0000000000000000 x1 0000000000000000 x2 0000000000000000 x3 0000000000000000
x4 0000000000000078 x5 0000000000000438 x6 000000000000075b x7 0000000000000000
x8 0000000000000000 x9 0000000000000000 x10 0000000000000000 x11 0000000200000004
x12 0000000000000000 x13 00000076c591c81c x14 00000076c5dcb768 x15 000000000000002f
x16 00000076c61fb1a4 x17 00000076bccfcc00 x18 00000073269de000 x19 0000000000000000
x20 0000000000000000 x21 0000000000000000 x22 0000000000000000 x23 0000000000000000
x24 0000000000000000 x25 0000000000000000 x26 0000000000000000 x27 0000000000000000
x28 0000000000000000 x29 000000733d1368f0
lr 00000076c5f5910c sp 000000733d1368f0 pc 00000076c5e6f358 pst 0000000020000000
backtrace:
#00 pc 000000000066f358 /system/lib64/libhwui.so (SkSurface::getCanvas()+20) (BuildId: 39c966654f116ad7df9bbbc37812164c)
https://github.com/Shopify/flash-list/issues/1 pc 0000000000759108 /system/lib64/libhwui.so (android::uirenderer::skiapipeline::GLFunctorDrawable::onDraw(SkCanvas*)+1612) (BuildId: 39c966654f116ad7df9bbbc37812164c)
https://github.com/Shopify/flash-list/pull/2 pc 0000000000727edc /system/lib64/libhwui.so (SkDrawable::draw(SkCanvas*, SkMatrix const*)+92) (BuildId: 39c966654f116ad7df9bbbc37812164c)
https://github.com/Shopify/flash-list/pull/3 pc 0000000000920768 /system/lib64/libhwui.so (SkGpuDevice::drawDrawable(SkDrawable*, SkMatrix const*, SkCanvas*)+356) (BuildId: 39c966654f116ad7df9bbbc37812164c)
https://github.com/Shopify/flash-list/pull/4 pc 0000000000735bd0 /system/lib64/libhwui.so (android::uirenderer::$_36::__invoke(void const*, SkCanvas*, SkMatrix const&) (.llvm.7336732046262659986)+132) (BuildId: 39c966654f116ad7df9bbbc37812164c)
https://github.com/Shopify/flash-list/pull/5 pc 000000000058154c /system/lib64/libhwui.so (android::uirenderer::skiapipeline::RenderNodeDrawable::drawContent(SkCanvas*) const+3568) (BuildId: 39c966654f116ad7df9bbbc37812164c)
https://github.com/Shopify/flash-list/pull/6 pc 00000000005805e4 /system/lib64/libhwui.so (android::uirenderer::skiapipeline::RenderNodeDrawable::onDraw(SkCanvas*)+240) (BuildId: 39c966654f116ad7df9bbbc37812164c)
https://github.com/Shopify/flash-list/pull/7 pc 00000000004e22c8 /system/lib64/libhwui.so (android::uirenderer::$_23::__invoke(void const*, SkCanvas*, SkMatrix const&) (.llvm.7336732046262659986)+88) (BuildId: 39c966654f116ad7df9bbbc37812164c)
https://github.com/Shopify/flash-list/pull/8 pc 000000000058154c /system/lib64/libhwui.so (android::uirenderer::skiapipeline::RenderNodeDrawable::drawContent(SkCanvas*) const+3568) (BuildId: 39c966654f116ad7df9bbbc37812164c)
https://github.com/Shopify/flash-list/issues/9 pc 00000000005805e4 /system/lib64/libhwui.so (android::uirenderer::skiapipeline::RenderNodeDrawable::onDraw(SkCanvas*)+240) (BuildId: 39c966654f116ad7df9bbbc37812164c)
https://github.com/Shopify/flash-list/issues/10 pc 00000000004e22c8 /system/lib64/libhwui.so (android::uirenderer::$_23::__invoke(void const*, SkCanvas*, SkMatrix const&) (.llvm.7336732046262659986)+88) (BuildId: 39c966654f116ad7df9bbbc37812164c)
https://github.com/Shopify/flash-list/issues/11 pc 000000000058154c /system/lib64/libhwui.so (android::uirenderer::skiapipeline::RenderNodeDrawable::drawContent(SkCanvas*) const+3568) (BuildId: 39c966654f116ad7df9bbbc37812164c)
https://github.com/Shopify/flash-list/issues/12 pc 00000000005805e4 /system/lib64/libhwui.so (android::uirenderer::skiapipeline::RenderNodeDrawable::onDraw(SkCanvas*)+240) (BuildId: 39c966654f116ad7df9bbbc37812164c)
https://github.com/Shopify/flash-list/issues/13 pc 00000000004e22c8 /system/lib64/libhwui.so (android::uirenderer::$_23::__invoke(void const*, SkCanvas*, SkMatrix const&) (.llvm.7336732046262659986)+88) (BuildId: 39c966654f116ad7df9bbbc37812164c)
https://github.com/Shopify/flash-list/issues/14 pc 000000000058154c /system/lib64/libhwui.so (android::uirenderer::skiapipeline::RenderNodeDrawable::drawContent(SkCanvas*) const+3568) (BuildId: 39c966654f116ad7df9bbbc37812164c)
https://github.com/Shopify/flash-list/issues/15 pc 00000000005805e4 /system/lib64/libhwui.so (android::uirenderer::skiapipeline::RenderNodeDrawable::onDraw(SkCanvas*)+240) (BuildId: 39c966654f116ad7df9bbbc37812164c)
https://github.com/Shopify/flash-list/issues/16 pc 00000000004e22c8 /system/lib64/libhwui.so (android::uirenderer::$_23::__invoke(void const*, SkCanvas*, SkMatrix const&) (.llvm.7336732046262659986)+88) (BuildId: 39c966654f116ad7df9bbbc37812164c)
https://github.com/Shopify/flash-list/issues/17 pc 000000000058154c /system/lib64/libhwui.so (android::uirenderer::skiapipeline::RenderNodeDrawable::drawContent(SkCanvas*) const+3568) (BuildId: 39c966654f116ad7df9bbbc37812164c)
https://github.com/Shopify/flash-list/issues/18 pc 00000000005805e4 /system/lib64/libhwui.so (android::uirenderer::skiapipeline::RenderNodeDrawable::onDraw(SkCanvas*)+240) (BuildId: 39c966654f116ad7df9bbbc37812164c)
https://github.com/Shopify/flash-list/issues/19 pc 00000000004e22c8 /system/lib64/libhwui.so (android::uirenderer::$_23::__invoke(void const*, SkCanvas*, SkMatrix const&) (.llvm.7336732046262659986)+88) (BuildId: 39c966654f116ad7df9bbbc37812164c)
#20 pc 000000000058154c /system/lib64/libhwui.so (android::uirenderer::skiapipeline::RenderNodeDrawable::drawContent(SkCanvas*) const+3568) (BuildId: 39c966654f116ad7df9bbbc37812164c)
#21 pc 00000000005805e4 /system/lib64/libhwui.so (android::uirenderer::skiapipeline::RenderNodeDrawable::onDraw(SkCanvas*)+240) (BuildId: 39c966654f116ad7df9bbbc37812164c)
https://github.com/Shopify/flash-list/issues/22 pc 00000000004e22c8 /system/lib64/libhwui.so (android::uirenderer::$_23::__invoke(void const*, SkCanvas*, SkMatrix const&) (.llvm.7336732046262659986)+88) (BuildId: 39c966654f116ad7df9bbbc37812164c)
https://github.com/Shopify/flash-list/issues/23 pc 000000000058154c /system/lib64/libhwui.so (android::uirenderer::skiapipeline::RenderNodeDrawable::drawContent(SkCanvas*) const+3568) (BuildId: 39c966654f116ad7df9bbbc37812164c)
https://github.com/Shopify/flash-list/issues/24 pc 00000000005851a4 /system/lib64/libhwui.so (android::uirenderer::skiapipeline::RenderNodeDrawable::forceDraw(SkCanvas*) const+200) (BuildId: 39c966654f116ad7df9bbbc37812164c)
https://github.com/Shopify/flash-list/issues/25 pc 00000000005ca574 /system/lib64/libhwui.so (android::uirenderer::skiapipeline::SkiaPipeline::renderLayersImpl(android::uirenderer::LayerUpdateQueue const&, bool)+784) (BuildId: 39c966654f116ad7df9bbbc37812164c)
https://github.com/Shopify/flash-list/pull/26 pc 00000000005c7a68 /system/lib64/libhwui.so (android::uirenderer::skiapipeline::SkiaPipeline::renderFrame(android::uirenderer::LayerUpdateQueue const&, SkRect const&, std::__1::vector<android::spandroid::uirenderer::RenderNode, std::__1::allocator<android::spandroid::uirenderer::RenderNode > > const&, bool, android::uirenderer::Rect const&, sk_sp, SkMatrix const&)+136) (BuildId: 39c966654f116ad7df9bbbc37812164c)
https://github.com/Shopify/flash-list/issues/27 pc 00000000005c75c0 /system/lib64/libhwui.so (android::uirenderer::skiapipeline::SkiaOpenGLPipeline::draw(android::uirenderer::renderthread::Frame const&, SkRect const&, SkRect const&, android::uirenderer::LightGeometry const&, android::uirenderer::LayerUpdateQueue*, android::uirenderer::Rect const&, bool, android::uirenderer::LightInfo const&, std::__1::vector<android::spandroid::uirenderer::RenderNode, std::__1::allocator<android::spandroid::uirenderer::RenderNode > > const&, android::uirenderer::FrameInfoVisualizer*)+436) (BuildId: 39c966654f116ad7df9bbbc37812164c)
https://github.com/Shopify/flash-list/issues/28 pc 000000000063c14c /system/lib64/libhwui.so (android::uirenderer::renderthread::CanvasContext::draw()+1496) (BuildId: 39c966654f116ad7df9bbbc37812164c)
https://github.com/Shopify/flash-list/pull/29 pc 000000000063aaa4 /system/lib64/libhwui.so (_ZNSt3__110__function6__funcIZN7android10uirenderer12renderthread13DrawFrameTask11postAndWaitEvE3$_0NS_9allocatorIS6_EEFvvEEclEv$c1671e787f244890c877724752face20+788) (BuildId: 39c966654f116ad7df9bbbc37812164c)
https://github.com/Shopify/flash-list/issues/30 pc 000000000064c444 /system/lib64/libhwui.so (android::uirenderer::WorkQueue::process()+160) (BuildId: 39c966654f116ad7df9bbbc37812164c)
https://github.com/Shopify/flash-list/issues/31 pc 000000000064c1a4 /system/lib64/libhwui.so (android::uirenderer::renderthread::RenderThread::threadLoop()+88) (BuildId: 39c966654f116ad7df9bbbc37812164c)
https://github.com/Shopify/flash-list/pull/32 pc 000000000001358c /system/lib64/libutils.so (android::Thread::_threadLoop(void*)+264) (BuildId: 748948a5650ad93d18b12eb1d9a51a89)
https://github.com/Shopify/flash-list/pull/33 pc 0000000000012de8 /system/lib64/libutils.so (thread_data_t::trampoline(thread_data_t const*)+408) (BuildId: 748948a5650ad93d18b12eb1d9a51a89)
https://github.com/Shopify/flash-list/issues/34 pc 00000000000b6e44 /apex/com.android.runtime/lib64/bionic/libc.so (__pthread_start(void*)+264) (BuildId: 73e145ce4e1dfca57a8eaf6d29c1d3fe)
https://github.com/Shopify/flash-list/issues/35 pc 0000000000053454 /apex/com.android.runtime/lib64/bionic/libc.so (__start_thread+68) (BuildId: 73e145ce4e1dfca57a8eaf6d29c1d3fe)

## To Reproduce

- run app on android 12 (real device or emulator) scroll up and down 

## Platform:

- [ ] iOS
- [x] Android

## Environment
"react": "18.0.0",
 "react-native": "0.69.1",
"@shopify/flash-list": "^1.2.1",

**Comment by naqvitalha** [comment] 2022-08-30 05:22
The crash seems to be originating in skia. Are you using react native skia by any chance?

**Comment by namnguyen211** [comment] 2022-08-30 06:21
No. i don't use react native skia

**Comment by fortmarek** [comment] 2022-08-30 10:40
Please, don't create new issues if you have already [created one before](https://github.com/Shopify/flash-list/issues/572). As mentioned in your original issue, we need a reproducible sample or at least more information to debug this. I will be closing this one, too – we can reopen it once we get more information to work with.

**Closed by fortmarek** 2022-08-30 10:40 UTC
Labels: bug
