### ISSUE TITLE
🅱️ Horizontal FlashList Bug (Layout Problem for height)

### ISSUE THREAD

**Issue by SherifMega** [Shopify/flash-list#782] opened 2023-03-08 14:16 UTC
## Current behavior

🅱️  Horizontal FlashList Bug (Layout Problem for height)
create Flashlist horizontal with any data try to switch from **portrait** - **landscape** - **portrait** again
you will see thats list height is not updated correctly **_(cropped!)_** and sounds cache previous height for landscape

regarding some investigation i made console.log from inside `_setFinalDimensions`
`console.log(this._totalWidth, ' - ', this._totalHeight)`
`recyclerlistview/dist/reactnative/core/layoutmanager/LayoutManager.js`

1250  -  952
530  -  952
500  -  952
500  -  696
❌ 500  -  696 **(should back again to correct height 952)**

also if you tried that from (onLayout) you will see that width and height not updated correctly
`
<FlashList
        onLayout={(event) => {
          console.warn(event.nativeEvent.layout.width, '-', event.nativeEvent.layout.height)
        }}
        horizontal
`

[bug.webm](https://user-images.githubusercontent.com/85056218/223732192-880a0307-cb43-4fc5-860c-99dc3fd586e6.webm)

## Expected behavior

List height should be full as it was in beginning before rotate.

## To Reproduce

 try to switch `horizontal` `flashlist` from **portrait** - **landscape** - **portrait** again
you will see list is cropped in height when back again to portrait
you can also check width and height from `onLayout` to check wrong values.

## Platform:

- [ ] iOS
- [ ] Android

## Environment

"@shopify/flash-list": "^1.4.1",
"expo": "~47.0.12",

**Comment by lucianobracco-geojam** [comment] 2023-03-09 18:57
Any solutions or ideas of how to overcome this issue?

**Comment by fortmarek** [comment] 2023-03-21 14:51
Thanks for flagging the issue. This is a duplicate of https://github.com/Shopify/flash-list/issues/581 that unfortunately hasn't been solved yet 😞 PRs are welcome!

**Closed by fortmarek** 2023-03-21 14:51 UTC
Labels: bug
